import type {
	ExpressiveCodeConfig,
	GiscusConfig,
	LicenseConfig,
	NavBarConfig,
	ProfileConfig,
	SiteConfig,
} from "./types/config";
import { LinkPreset } from "./types/config";

export const siteConfig: SiteConfig = {
	title: "YunDuan-F",
	subtitle: "Personal Blog",
	// EDIT HERE: default interface language. Use "en" for English navigation text.
	lang: "en",
	themeColor: {
		// EDIT HERE: site theme color hue. It is fixed at 230 and visitors cannot change it.
		hue: 230,
		fixed: true,
	},
	banner: {
		enable: true,
		// EDIT HERE: light mode banner image.
		src: "assets/images/background/white.jpg",
		// EDIT HERE: dark mode banner image. Leave empty or remove this line to reuse src.
		darkSrc: "assets/images/background/black.jpg",
		// EDIT HERE: image crop position. Supports "top", "center", or "bottom".
		position: "center",
		credit: {
			enable: false,
			// EDIT HERE: banner image credit text, if credit.enable is true.
			text: "",
			// EDIT HERE: optional credit link, if credit.enable is true.
			url: "",
		},
	},
	toc: {
		enable: true, // Display the table of contents on the right side of the post
		depth: 3, // Maximum heading depth to show in the table, from 1 to 3
	},
	favicon: [
		// Leave this array empty to use the default favicon
		// {
		//   src: '/favicon/icon.png',    // Path of the favicon, relative to the /public directory
		//   theme: 'light',              // (Optional) Either 'light' or 'dark', set only if you have different favicons for light and dark mode
		//   sizes: '32x32',              // (Optional) Size of the favicon, set only if you have favicons of different sizes
		// }
	],
};

export const navBarConfig: NavBarConfig = {
	links: [
		LinkPreset.Home,
		LinkPreset.Archive,
		LinkPreset.About,
	],
	// EDIT HERE: navbar "More" dropdown items. Add future header dropdown links here.
	moreLinks: [
		{
			name: "Tools",
			url: "/tools/",
		},
		{
			name: "Friends",
			url: "/friends/",
		},
	],
};

export const profileConfig: ProfileConfig = {
	// EDIT HERE: sidebar avatar image. Relative to /src, or use an absolute /public path starting with "/".
	avatar: "assets/images/Avatar/avatar.jpg",
	name: "YunDuan-F",
	bio: "在这里记录一些东西",
	// EDIT HERE: links displayed below the sidebar avatar.
	links: [
		{
			name: "GitHub",
			icon: "fa6-brands:github",
			url: "https://github.com/YunDuan-F",
		},
	],
};

export const licenseConfig: LicenseConfig = {
	enable: true,
	name: "CC BY-NC-SA 4.0",
	url: "https://creativecommons.org/licenses/by-nc-sa/4.0/",
};

export const giscusConfig: GiscusConfig = {
	// EDIT HERE: GitHub login comments. Fill the fields from https://giscus.app and set enable to true.
	enable: true,
	// EDIT HERE: public GitHub repository used for comments, for example "YunDuan-F/YunDuan-F.github.io".
	repo: "YunDuan-F/YunDuan-F.github.io",
	// EDIT HERE: generated by https://giscus.app after the repository is selected.
	repoId: "R_kgDORbEuHQ",
	// EDIT HERE: GitHub Discussions category name, for example "Announcements" or "General".
	category: "Announcements",
	// EDIT HERE: generated by https://giscus.app after the category is selected.
	categoryId: "DIC_kwDORbEuHc4C9nzj",
	mapping: "pathname",
	strict: "0",
	reactionsEnabled: "1",
	emitMetadata: "0",
	inputPosition: "bottom",
	theme: "preferred_color_scheme",
	lang: "en",
	loading: "lazy",
};

export const expressiveCodeConfig: ExpressiveCodeConfig = {
	// EDIT HERE: syntax highlighting themes for Markdown code blocks.
	lightTheme: "github-light",
	darkTheme: "github-dark",
};
